# products.yaml
# Add your product pages here.
# For each product, specify:
# - name: friendly label
# - url: product page
# - selector: CSS selector that matches the price element
# - target_price: notify when current price <= this (optional)

products:
  - name: "DecksDirect Fascia Mount Post Kit"
    url: "https://www.decksdirect.com/skyline-fascia-mount-post-for-cable-railing.html"
    selector: "script:contains('finalPrice')"    
    target_price: 40.00

  # Example static page:
  # - name: "Example Store Widget"
  #   url: "https://store.example.com/widget"
  #   selector: "span.price"
  #   target_price: 19.99
