# products.example.yaml
# Example configuration file for the price watcher
# Copy this file to products.yaml and customize with your own products.

products:
  - name: "Example Product 1"
    url: "https://www.example.com/product1"
    selector: "span.price"        # CSS selector or regex:<pattern>
    target_price: 99.99

  - name: "Example Product 2 (regex mode)"
    url: "https://www.example.com/product2"
    selector: "regex:\"finalPrice\"\\s*:\\s*\\{\"amount\"\\s*:\\s*([0-9.]+)\\}"
    target_price: 49.99

